### ISSUE TITLE
Outdated in 2.3?

### ISSUE THREAD

**Issue by stevenhoney** [BFTrick/woocommerce-integration-demo#1]
Just went back to a plug-in I'd been playing with a while back and in 2.3 the previously registered settings form I'd created under Settings > Integrations tab no longer display?
Used this as a boilerplate originally so is this now out-dated and if so any chance of a working update?
Example code I was using here:
https://github.com/SteveHoneyNZ/wc-pwinty/blob/master/includes/class-wc-integration-pwinty-integration.php

**Comment by BFTrick** [comment]
I just reinstalled this and it's working fine for me. Not sure what happened to your integration so that it doesn't work anymore. :(
